export const types = Object.freeze({
  DATA_REQUEST: 'DATA_REQUEST',
  DATA_SUCCESS: 'DATA_SUCCESS',
  DATA_FAILURE: 'DATA_FAILURE',
  REMOVE_ITEM: 'REMOVE_ITEM',
  ON_TOGGLE_PROPERTIES: 'ON_TOGGLE_PROPERTIES',
  ON_ADD_ITEM: 'ON_ADD_ITEM',
  ON_SEARCH_ITEMS: 'ON_SEARCH_ITEMS',
  ON_EDIT_ITEM: 'ON_EDIT_ITEM',
  ON_ALL_ITEMS_DONE: 'ON_ALL_ITEMS_DONE',
});
