export const types = Object.freeze({
  DATA_REQUEST: 'DATA_REQUEST',
  DATA_SUCCESS: 'DATA_SUCCESS',
  DATA_FAILURE: 'DATA_FAILURE',
  REMOVE_ITEM: 'REMOVE_ITEM',
  ON_TOGGLE_PROPERTIES: 'ON_TOGGLE_PROPERTIES',
});
