export const asyncTypes = Object.freeze({
  GET_DATA_ASYNC: 'GET_DATA_ASYNC',
  REMOVE_ITEM_ASYNC: 'REMOVE_ITEM_ASYNC',
  TOGGLE_PROPERTIES_ASYNC: 'TOGGLE_PROPERTIES_ASYNC',
  ADD_ITEM_ASYNC: 'ADD_ITEM_ASYNC',
  SEARCH_ITEMS_ASYNC: 'SEARCH_ITEMS_ASYNC',
  EDIT_ITEM_ASYNC: 'EDIT_ITEM_ASYNC',
  ALL_ITEMS_DONE_ASYNC: 'ALL_ITEMS_DONE_ASYNC',
});
